**NUMPY**

**1D ARRAY**

In [2]:
from matplotlib import pyplot as plt
import numpy as np

In [8]:
scores = np.array([85,90,100,58,67,75,81,65,63,61,74,80,89,64,72,70,78])
print(scores)
print('Mean =',np.mean(scores))
print('Standard Deviation =',np.std(scores))
print('Max = ',np.max(scores))
print('min =',np.min(scores))

[ 85  90 100  58  67  75  81  65  63  61  74  80  89  64  72  70  78]
Mean = 74.82352941176471
Standard Deviation = 11.283696172263701
Max =  100
min = 58


In [11]:
print(scores + 5)
print(scores / 100)

[ 90  95 105  63  72  80  86  70  68  66  79  85  94  69  77  75  83]
[0.85 0.9  1.   0.58 0.67 0.75 0.81 0.65 0.63 0.61 0.74 0.8  0.89 0.64
 0.72 0.7  0.78]


In [18]:
print(scores[scores >= 70])
print(np.sum(scores >= 70))


[ 85  90 100  75  81  74  80  89  72  70  78]
11


**2D ARRAY**

In [21]:
grades = np.array([
    [85,97,79,99],
    [80,80,71,69],
    [76,67,95,75],
    [100,90,92,81],
    [79,84,86,88]
])
print(np.mean(grades, axis=1))  #row
print(np.mean(grades, axis=0))   #column

[90.   75.   78.25 90.75 84.25]
[84.  83.6 84.6 82.4]


**Indexing & Slicing**

In [27]:
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[1:4])
print(arr[[0,2,4]])
print(arr[arr > 25])

10
[20 30 40]
[10 30 50]
[30 40 50]


In [32]:
matrix = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])
print(matrix[0,0])       #[row,column]    เป็น index น้า!
print(matrix[1,1])
print(matrix[2,4])


1
7
15


In [42]:
print(matrix[0,:])
print(matrix[:,0])
print('--------------------------------------')
print(matrix[0:2,1:4])   #row 0 1  & column 1 2 3
print('--------------------------------------')
print(matrix[-1:,0:-2])   #นับถอยหลัง ถ้า -



[1 2 3 4 5]
[ 1  6 11]
--------------------------------------
[[2 3 4]
 [7 8 9]]
--------------------------------------
[[11 12 13]]


**Broadcasting**

In [45]:
print(np.array([1,2,3] ) + 10)
print(np.array([
    [1,2,3],
    [4,5,6]
])
+ np.array([100,200,300]) )

[11 12 13]
[[101 202 303]
 [104 205 306]]


**Reshape & Flatten**

In [53]:
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))  #ขนาด 2 row x 3 column
print(arr.reshape(3,2))  #ขนาด 3 row x 2 column
print(arr.reshape(2,-1))
print(arr.reshape(-1,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [55]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


**Random**

In [65]:
np.random.seed(42)   #seed เปลี่ยน ได้ชุดใหม่
print(np.random.rand(5))    # 0-1
print(np.random.rand(2,2))
print(np.random.randint(0,100, size = 5))  #กำหนดเอง
print('--------------------------------------------')
print(np.random.randn(5))   #ออกใกล้ 0 (ระฆัง) แลไม่จำกัดช่วง


[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
[[0.15599452 0.05808361]
 [0.86617615 0.60111501]]
[23  2 21 52  1]
--------------------------------------------
[ 0.23309524  0.11799461  1.46237812  1.53871497 -2.43910582]


**Linear Algebra**

**Matrix multiplication**

In [70]:
A = np.array([[1,2],
                     [3,4]
])
B = np.array([[5,6],
                     [7,8]
])

print(A*B)
print('---------------------------------------------------------')
print(A @ B)
                      # [0,0]
                      # row 0 A  x  column 0 B
                     # (1x5) + (2x7) = 19

                     #[0,1]
                     #row  0 A  x  column 1 B
                     # (1x6) + (2x8) = 22

                     #[1,0]
                     #row  1 A  x  column 0 B
                     #(3x5) + (4x7) = 43

                     #[1,1]
                     #row 1 A  x  column 1 B
                     #(3x6) + (4x8)



[[ 5 12]
 [21 32]]
---------------------------------------------------------
[[19 22]
 [43 50]]


In [78]:
C = np.array([
    [1,2,3],
    [4,5,6]
])
D = np.array([
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

try :
  C * D
except Exception as e:
  print(f"Error : {e}")

print(C @ D)               # 2x3 + 3x4  = 2x4
                                  # because  2 = row A  x  4 = column B
                                  #สรุป คือ เลือกตำแหน่งแรก และท้ายสุด (2,4)

#แถว 0 ของ A = [1, 2, 3]
#[0,0]: [1,2,3] • [5, 9,13]  = (1×5)+(2×9)+(3×13)  = 5+18+39  = 62
#[0,1]: [1,2,3] • [6,10,14]  = (1×6)+(2×10)+(3×14) = 6+20+42  = 68
#[0,2]: [1,2,3] • [7,11,15]  = (1×7)+(2×11)+(3×15) = 7+22+45  = 74
#[0,3]: [1,2,3] • [8,12,16]  = (1×8)+(2×12)+(3×16) = 8+24+48  = 80

#แถว 1 ของ A = [4, 5, 6]
#[1,0]: [4,5,6] • [5, 9,13]  = (4×5)+(5×9)+(6×13)  = 20+45+78  = 143
#[1,1]: [4,5,6] • [6,10,14]  = (4×6)+(5×10)+(6×14) = 24+50+84  = 158
#[1,2]: [4,5,6] • [7,11,15]  = (4×7)+(5×11)+(6×15) = 28+55+90  = 173
#[1,3]: [4,5,6] • [8,12,16]  = (4×8)+(5×12)+(6×16) = 32+60+96  = 188


Error : operands could not be broadcast together with shapes (2,3) (3,4) 
[[ 62  68  74  80]
 [143 158 173 188]]


**Transpose**

In [79]:
A = np.array([[1,2],
                     [3,4]
])

print(A.T)    #row --> column
                  #column --> row

[[1 3]
 [2 4]]


In [80]:
B = np.array([
    [1,2,3],
    [4,5,6]
])

print(B.T)

[[1 4]
 [2 5]
 [3 6]]


**Inverse**

In [82]:
I = np.array([
    [1,0],
    [0,1]
])

A = np.array([
    [1,2],
    [3,4]
])

print(A @ I)

print('-------------------------------')

print(np.linalg.inv(A))
#[a,b] --> [d,-b]
#[c,d] --> [-c,a]

#[4,-2]
#[-3,1]

#det = (1x4) - (2x3) = -2
#หารทุกตัวด้วย det

[[1 2]
 [3 4]]
-------------------------------
[[-2.   1. ]
 [ 1.5 -0.5]]


In [83]:
B = np.array([
    [1,2],
    [2,4]
])

try :
  np.linalg.inv(B)
except Exception as e:
  print(f"Error : {e}")

#ERROR
#det = 0
#หารด้วย 0 ไม่ได้

Error : Singular matrix


Det = Determinant

In [87]:
print(np.linalg.det(B))
print(np.linalg.det(A))
print(np.linalg.det(I))

0.0
-2.0000000000000004
1.0
